[theme]

# Primary color for interactive elements
primaryColor = "#d33682"

# Background color for main content area
backgroundColor = "#002b36"

# Background color for sidebar and interactive widgets"
secondaryBackgroundColor = "#586e75"

# Color used for almost all text
textColor = "#fff"